### ISSUE TITLE
[Help] Setup on vercel

### ISSUE THREAD

**Issue by dhobi** [jeffersonmourak/voting.poker#1]
What I have done so far:
- I forked this project and deployed it to Vercel. 
- After seeing some errors around Firebase I've set up a Firebase project and created a Firestore database. 
- I added the "NEXT_PUBLIC_FIREBASE" variables to Vercel environment

When I allow ALL read, write access in the Firestore rules, voting.poker is working fine.

As there is no documentation on how to do the setup exactly, I wanted to ask though:
- Are these steps correct or is there any other method to get voting.poker running?
- Is it possible to connect to Firestore without allowing access to ALL users? Something like:
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```
My goal would be to create some minimal Vercel guide for the next guy trying to set it up (PR) 😃

**Comment by jeffersonmourak** [comment]
I've just updated the code to be easier to deploy on vercel 😄, now you just need an `Ably` key
https://ably.com/
