### ISSUE TITLE
Scroll bar flickering within voting interface

### ISSUE THREAD

**Issue by lilyloop** [jeffersonmourak/voting.poker#11]
**Description:**

The scroll bar in the voting interface on the Voting Poker website (https://www.voting.poker/) is flickering in and out incessantly within the voting interface when using Firefox. This issue disrupts the user experience, making it difficult to interact with the interface smoothly.

**Steps to Reproduce:**

1.  Open Firefox (latest version).
2. Navigate to the Voting Poker website (https://www.voting.poker/).
3. Access the voting interface.
4. Observe the behavior of the scroll bar.

**Expected Behavior:**

The scroll bar should remain static or only appear when necessary, without flickering or causing visual disruption.

**Actual Behavior:**

The scroll bar flickers in and out rapidly, creating a distracting and jarring experience.

Browser: Firefox 129.0
Operating System: MacOS 14.6.1

**Additional Information:**

- This issue may also occur in Chrome and Brave browsers.
- Clearing the cache and cookies in Firefox did not resolve the issue.
- The behavior persists in both normal and private browsing modes.

**Comment by jeffersonmourak** [comment]
Hi @lilyloop, thanks for the issue; wanna confirm with you that this is the behavior you're referencing above.
https://github.com/user-attachments/assets/86b52479-d7fd-4cfd-b612-d87ab87c9113

If so, yeah, that's a very annoying visual defect. I don't know exactly what is causing that, but I will try to take some time this weekend to check on this.

**Comment by lilyloop** [comment]
Thanks for the quick response here! Unfortunately it's a bit worse in desktop:

https://github.com/user-attachments/assets/01ee3d45-bc3d-4bdf-8926-5f383ae4163b

**Comment by lilyloop** [comment]
Thanks for the quick engagement here!

Unfortunately, it's even a bit worse than that video on desktop:

https://github.com/user-attachments/assets/db0c01d1-b2f9-4452-9110-fa153a38e32c

**Comment by jeffersonmourak** [comment]
@lilyloop just pushed a fix to the main branch, and it should now be live.
Again thanks a lot for the help finding that out 😄

<img src="https://media1.giphy.com/media/26DMWoEcQiE5sA7EQ/giphy.gif"/>
